name: Update Production

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  update-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge master -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}
